apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-pipeline
  namespace: data-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-pipeline
  template:
    metadata:
      labels:
        app: data-pipeline
    spec:
      containers:
        - image: ghcr.io/klimatbyran/data-pipeline:1.1.1 # {"$imagepolicy": "flux-system:data-pipeline"}
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          name: data-pipeline
          ports:
            - containerPort: 80
          env:
            - name: DEBUG
              value: 'true'
            - name: DISCORD_APPLICATION_ID
              valueFrom:
                secretKeyRef:
                  name: env
                  key: DISCORD_APPLICATION_ID
            - name: DISCORD_SERVER_ID
              valueFrom:
                secretKeyRef:
                  name: env
                  key: DISCORD_SERVER_ID
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: env
                  key: DISCORD_TOKEN
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: env
                  key: OPENAI_API_KEY
            - name: OPENAI_ORG_ID
              valueFrom:
                secretKeyRef:
                  name: env
                  key: OPENAI_ORG_ID
            - name: CHROMA_HOST
              valueFrom:
                secretKeyRef:
                  name: env
                  key: CHROMA_HOST
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred
