---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: garbo
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    cert-manager.io/cluster-issuer: 'letsencrypt-prod'
    external-dns.alpha.kubernetes.io/hostname: garbo.klimatkollen.se.
spec:
  tls:
    - hosts:
        - garbo.klimatkollen.se
      secretName: garbo-klimatkollen-se-tls

  rules:
    - host: garbo.klimatkollen.se
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: garbo
                port:
                  number: 80
