apiVersion: apps/v1
kind: Deployment
metadata:
  name: nlm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nlm
  template:
    metadata:
      labels:
        app: nlm
    spec:
      containers:
        - image: ghcr.io/nlmatics/nlm-ingestor
          resources:
            limits:
              cpu: 1000m
              memory: 2Gi
          name: nlm
          ports:
            - containerPort: 5001
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: nlm
spec:
  ports:
    - port: 5001
      targetPort: 5001
  selector:
    app: nlm
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nlm
  annotations:
    cert-manager.io/cluster-issuer: 'letsencrypt-prod'
spec:
  tls:
    - hosts:
        - nlm.klimatkollen.se
      secretName: nlm-klimatkollen-se-tls

  rules:
    - host: nlm.klimatkollen.se
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nlm
                port:
                  number: 5001
