apiVersion: apps/v1
kind: Deployment
metadata:
  name: nlm-ingestor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nlm-ingestor
  template:
    metadata:
      labels:
        app: nlm-ingestor
    spec:
      containers:
        - image: ghcr.io/nlmatics/nlm-ingestor
          resources:
            limits:
              cpu: 500m
              memory: 2Gi
          name: nlm-ingestor
          ports:
            - containerPort: 5001
          imagePullPolicy: Always
      #imagePullSecrets:
      #  - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: nlm-ingestor
spec:
  ports:
    - port: 5001
      targetPort: 5001
  selector:
    app: nlm-ingestor
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nlm-ingestor
  annotations:
    cert-manager.io/cluster-issuer: 'letsencrypt-prod'
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
spec:
  tls:
    - hosts:
        - nlm-ingestor.klimatkollen.se
      secretName: nlm-ingestor-klimatkollen-se-tls

  rules:
    - host: nlm-ingestor.klimatkollen.se
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nlm-ingestor
                port:
                  number: 5001
