apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
spec:
  template:
    metadata:
      annotations:
        kustomize.toolkit.fluxcd.io/substitute: disabled
    spec:
      restartPolicy: Never
      containers:
        - name: migration
          image: ghcr.io/klimatbyran/garbo
          command: ['npm', 'run', 'migrate']
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: postgres-password
            - name: DATABASE_URL
              value: postgresql://postgres:$(POSTGRES_PASSWORD)@postgresql:5432/garbo
