apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-migration
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-migration
  template:
    metadata:
      labels:
        app: db-migration
      annotations:
        kustomize.toolkit.fluxcd.io/substitute: disabled
    spec:
      containers:
        - name: migration
          image: ghcr.io/klimatbyran/garbo
          imagePullPolicy: Always
          command: ['sh', '-c']
          args:
            - |
              npm run migrate
              while true; do
                sleep 3600
              done
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: postgres-password
            - name: DATABASE_URL
              value: postgresql://postgres:$(POSTGRES_PASSWORD)@postgresql:5432/garbo
