apiVersion: batch/v1
kind: Job
metadata:
  generateName: db-migration-
spec:
  ttlSecondsAfterFinished: 3600 # Job tas bort en timme efter att den slutförts
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migration
          image: ghcr.io/klimatbyran/garbo
          command: ['npm', 'run', 'migrate']
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: postgres-password
            - name: DATABASE_URL
              value: postgresql://postgres:$(POSTGRES_PASSWORD)@postgresql:5432/garbo
