apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: garbo

resources:
  - ../../base

patches:
  - path: ingress-patch.yaml

images:
  - name: ghcr.io/klimatbyran/garbo
    newName: ghcr.io/klimatbyran/garbo
    newTag: '3.6.7' # {"$imagepolicy": "flux-system:garbo"}
