apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: garbo
resources:
  - ../../base
patches:
  - path: ingress-patch.yaml
images:
  - name: ghcr.io/klimatbyran/garbo
    newName: ghcr.io/klimatbyran/garbo
    newTag: 'ghcr.io/klimatbyran/garbo:3.7.0' # {"$imagepolicy": "flux-system:garbo"}

transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: production-namespace-transformer
      namespace: garbo
    unsetOnly: true
