---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: garbo
  annotations:
    kubernetes.io/ingress.class: 'gce'
    cert-manager.io/cluster-issuer: 'letsencrypt-prod'
    kubernetes.io/ingress.global-static-ip-name: 'garbo-ip'
    networking.gke.io/managed-certificates: 'managed-cert'
    networking.gke.io/v1beta1.FrontendConfig: 'garbo-frontend-config'
spec:

  rules:
    - host: api.klimatkollen.se
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: garbo
                port:
                  number: 80
