name: Continuous Integration

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'k8s/**'
      - 'Dockerfile.base'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🔧 Setup GitHub CLI
        run: |
          type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y

      - id: imagename
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.repository }}

      - name: 📝 Get Current Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main

      - name: 🔐 Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 🏗️ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: 🔧 Build and push Docker Image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ steps.imagename.outputs.lowercase }}:${{ steps.package-version.outputs.current-version}}
            ${{ env.REGISTRY }}/${{ steps.imagename.outputs.lowercase }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: 🎫 Update patch version
        id: version
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          NEW_VERSION=$(npm version patch)
          echo "new_version=${NEW_VERSION}" >> $GITHUB_OUTPUT
          git push origin main

      - name: 📝 Create GitHub Release for Minor Version
        if: endsWith(steps.version.outputs.new_version, '.0')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get changes since last release
          LAST_TAG=$(git describe --tags --abbrev=0 --exclude ${NEW_VERSION})
          CHANGELOG=$(git log ${LAST_TAG}..HEAD --pretty=format:"* %s")
          
          # Create GitHub release
          gh release create ${NEW_VERSION} \
            --title "Release ${NEW_VERSION}" \
            --notes "${CHANGELOG}" \
            --generate-notes
