apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: garbo-stage
resources:
  - ../../base
patches:
  - path: ingress-patch.yaml
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: worker
      spec:
        replicas: 2

images:
  - name: ghcr.io/klimatbyran/garbo
    newName: ghcr.io/klimatbyran/garbo
    newTag: 3.7.0 # {"$imagepolicy": "flux-system:garbo-stage"}
