apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stage-garbo

resources:
  - ../../base

patches:
  - path: ingress-patch.yaml

images:
  - name: ghcr.io/klimatbyran/garbo
    newTag: # {"$imagepolicy": "flux-system:garbo-stage"}
